---
# Kubernetes cluster configuration
registry_url: "your-registry-url"  # Replace with your container registry URL
app_name: portfolio-website
image_name: portfolio-website
image_tag: latest
replicas: 2
namespace: default
container_port: 80
service_port: 80

# Resource limits
resource_limits:
  cpu: "0.5"
  memory: "512Mi"
resource_requests:
  cpu: "0.2"
  memory: "256Mi"

# Deployment strategy
deployment_strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0 